[Interface]
PrivateKey = yN+EVvpIZjqI4po+lkWqE4vwTPXBkvIWRum7PnRdcms=
Address = 10.0.0.1/24
ListenPort = 6111

[Peer]
PublicKey = lXmFE2wV8O4KeBEEhwV6Y8xjMK174wyiMwuUTnd+vSE=
Endpoint = 127.0.0.1:5111
AllowedIPs = 10.0.0.0/24
