[Interface]
PrivateKey = 6ME8bdMZKkD8f/RvVWY/JfuCI42SKUxphKhcPlXUHU8=
Address = 10.0.0.2/24
ListenPort = 6222

[Peer]
PublicKey = kutEL8kQJaLgU7tOLXwvKTnRDgDplD/Co6fgennYRik=
AllowedIPs = 10.0.0.0/24
